version: '3.8'

services:
  web:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3333:3333"
    volumes:
      - ../public:/app/public
      - ../data:/app/data
      - ../config:/app/config
      - ../server:/app/server
    environment:
      - NODE_ENV=production
      - PORT=3333
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=whiffwonder2024
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - ../config/redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  app-network:
    driver: bridge
    internal: true

volumes:
  redis_data:
